"""
Django settings for trabajoFinalCHD_RC project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a0ba^prp4nrugdg3@+tkwmk#fyric$0^4058#fbg-v$nn_!jrv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'trabajofinalchd-rc.onrender.com',
    'localhost',  # opcional, para desarrollo local
    '127.0.0.1',  # opcional, para desarrollo local
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Aplicaciones.gestionArriendo',
    'pwa',
]

AUTH_USER_MODEL = 'gestionArriendo.Usuario'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Agrega esta línea justo después de SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'trabajoFinalCHD_RC.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Aplicaciones.gestionArriendo.context_processors.usuario_actual',
            ],
        },
    },
]

WSGI_APPLICATION = 'trabajoFinalCHD_RC.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'arriendoutc',
        'USER': 'cristian',
        'PASSWORD': 'dMVNuHDquXIn25J8BAjuSc8ax2tExiJf',
        'HOST': 'dpg-d1uuqsbuibrs738s9dj0-a.oregon-postgres.render.com',
        'PORT': '5432',
    }
}
'''

#bdd david

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'trabajoArriendo.sqlite3',
    }
}
'''



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR,'trabajoFinalCHD_RC/static'),)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL='/media/'
MEDIA_ROOT=(os.path.join(BASE_DIR,'trabajoFinalCHD_RC/media/'))


TELEGRAM_BOT_TOKEN = '8098744858:AAFH0nA0azl6kc72z57VjQchXpwyh-vTgm0'



# CONFIGURACION SMTP DE GMAIL
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'cristianroblero00@gmail.com' # Tu correo electrónico
EMAIL_HOST_PASSWORD = 'ljfl ckga maws oxwr ' 

PWA_APP_NAME = 'Mi Aplicación PWA'
PWA_APP_SHORT_NAME = 'MiApp'
PWA_APP_DESCRIPTION = "Esta es mi app progresiva"
PWA_APP_THEME_COLOR = '#317EFB'
PWA_APP_BACKGROUND_COLOR = '#FFFFFF'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'portrait'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'

PWA_APP_ICONS = [
    {'src': '/static/plantilla/pwa/icons/icon-192.png', 'sizes': '192x192'},
    {'src': '/static/plantilla/pwa/icons/icon-512.png', 'sizes': '512x512'},
]

PWA_APP_ICONS_APPLE = [
    {'src': '/static/plantilla/pwa/icons/icon-192.png', 'sizes': '192x192'},
    {'src': '/static/plantilla/pwa/icons/icon-512.png', 'sizes': '512x512'},
]

PWA_APP_SPLASH_SCREEN = [
    {
        
        'media': '(device-width: 640px) and (device-height: 1136px)'
    }
]

PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'static', 'plantilla', 'pwa', 'js', 'serviceworker.js')
