# Generated by Django 5.2 on 2025-06-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionArriendo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
