# Generated by Django 5.2 on 2025-06-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionArriendo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.TextField(blank=True, null=True),
        ),
    ]
