# Generated by Django 5.2 on 2025-07-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionArriendo', '0002_alter_publicacion_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='latitud',
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='longitud',
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
    ]
