# Generated by Django 5.2 on 2025-07-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionArriendo', '0003_alter_publicacion_latitud_alter_publicacion_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialeliminacion',
            name='descripcion_publicacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialeliminacion',
            name='titulo_publicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
