# Generated by Django 5.2 on 2025-06-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionArriendo', '0003_usuario_email_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.TextField(blank=True, default='Arrendatario', null=True),
        ),
    ]
