# Generated by Django 5.2 on 2025-07-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionArriendo', '0004_historialeliminacion_descripcion_publicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='numeroPublicaciones',
            field=models.IntegerField(default=0),
        ),
    ]
